version: '3.8'
services:
  antivirus:
    build: .
    container_name: clamav
    environment:
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - ALERT_EMAIL=${ALERT_EMAIL}
      - VPN_USER=${VPN_USER}
      - VPN_PASSWORD=${VPN_PASSWORD}
    volumes:
      - ./Scripts:/Scripts
      - /mnt/DATA:/scandir:ro
      - ./quarantine:/quarantine
      - ./clamav_db:/var/lib/clamav
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: unless-stopped